### ISSUE TITLE
How were the users chosen? 

### ISSUE THREAD

**Issue by Santosh-Gupta** [MengtingWan/goodreads#2]
I see that there are 876,145 total users in the dataset, but goodreads has 90 million users (as of july 2019). I was wondering how were those 876,145 users selected. Was there a minimum number of ratings?

**Comment by MengtingWan** [comment]
Hi Santosh, the users in these dataset are those who in the top 1000 book clubs (https://www.goodreads.com/group) back to early 2017 & chose to public their book shelves - so they are just a subset of the Goodreads community.

**Comment by Santosh-Gupta** [comment]
Are there any plans for an entire goodreads user review dataset? 

I started a script here, but it needs some work 

https://colab.research.google.com/drive/1uOyVlKaT4QFtce9yQpKj9hRtj5z8Uyta

It downloads reviews directly from rss feeds.
