### ISSUE TITLE
dataset links uncreachable

### ISSUE THREAD

**Issue by leonardozilli** [MengtingWan/goodreads#6]
all the links to the datasets listed in the [datasets](https://mengtingwan.github.io/data/goodreads.html#datasets) section of the webpage return a 404 error.

**Comment by jesseAvgonzsmi** [comment]
Seconding this!

**Comment by samihandani** [comment]
Also having trouble with this.

**Comment by MengtingWan** [comment]
Thanks for flagging this folks! The entire dataset server is down now and I'm pinging people to investigate. Will keep folks posted here as I hear any updates. Thanks very much for your patience!

**Comment by MengtingWan** [comment]
> Thanks for flagging this folks! The entire dataset server is down now and I'm pinging people to investigate. Will keep folks posted here as I hear any updates. Thanks very much for your patience!

Hi folks, closing this issue as looks like the server is up and running - you should be able to download the dataset now.
