### ISSUE TITLE
Goodreads dataset no longer available?

### ISSUE THREAD

**Issue by dcheng1248** [MengtingWan/goodreads#8]
Hello! I'm a university student who has been using your goodreads dataset to experiment with some ML techniques and learn. I noticed since yesterday that the dataset is no longer available. Would this change be permanent? If so, would there be any chance I could get a compressed version of the data for my own learning purposes? Thanks!

In any case, I want to thank you for providing the very useful data! I have learnt a lot from it.

**Comment by MengtingWan** [comment]
Hi sorry for the late reply. I think the [download links](https://mengtingwan.github.io/data/goodreads.html) are back on, but feel free to let me know if there're any issues.
