### ISSUE TITLE
Is this data set not available for download?

### ISSUE THREAD

**Issue by LWSupup** [MengtingWan/goodreads#9]
Sorry to bother you, I am a student in school, looking for a detailed data set of book user interaction, if possible, could you please send me a data set? Thank you very much indeed!!

**Comment by MengtingWan** [comment]
Hi sorry for the late reply. I think the [download links](https://mengtingwan.github.io/data/goodreads.html) are back on, but feel free to let me know if there're any issues.

**Comment by LWSupup** [comment]
Thank you very much!&nbsp;








 ----------Reply to Message----------
 On Thu, Jul 11, 2024 07:42 AM Mengting ***@***.***&gt; wrote:

  

 
Hi sorry for the late reply. I think the download links are back on, but feel free to let me know if there're any issues.

**Comment by HarshAmreliya** [comment]
Hey, sorry to bother you, but the links are not working. I am a college student trying to experiment on this dataset. Would be great if i could get the dataset somehow.

**Comment by MengtingWan** [comment]
Hi @HarshAmreliya  - could you try the download links in this website? https://cseweb.ucsd.edu/~jmcauley/datasets/goodreads.html
The datasets have been moved to a new server lately and the old links no longer work.
